name: Docker Image CI

on:
  push:
    branches: [ ci ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: ilteoood/docker_buildx@master
        name: Build & push Docker image
        with:
          publish: true
          imageName: miclon/puppeteer-render
          tags: latest
          platform: linux/amd64,linux/arm64,linux/arm/v7
          dockerHubUser: ${{ secrets.DOCKER_USERNAME }}
          dockerHubPassword: ${{ secrets.DOCKER_PASSWORD }}
